
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmnxrploqtbztkghziev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tbnhycGxvcXRienRrZ2h6aWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTM5MTMsImV4cCI6MjA1Nzg4OTkxM30.WieYbGAMd0lX3EUZUewHf_qiAArfaRW3rQdUf8mTbNc";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});
